# Wrangler 設定ファイル

# --------------------------------------------------
# 本番デプロイ設定
# --------------------------------------------------
name = "drabaka"
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB" # アプリケーションからアクセスする名前
database_name = "drabaka-DB"
database_id = "48c5e67c-c9c5-40ea-b23c-e7d1fd7ae170"

# --------------------------------------------------
# プレビュー環境 ("wrangler pages dev" やプレビューデプロイ) の設定
# --------------------------------------------------
[env.preview]

[[env.preview.d1_databases]]
binding = "DB"
database_name = "drabaka-db-local" # ローカル用のDB名
database_id = "local-dev-db"
