name = "drabaka-worker"
compatibility_date = "2025-09-20"

[assets]
directory = "./.next" # Next.jsのビルド出力ディレクトリ

[[d1_databases]]
binding = "DB"
database_name = "drabaka-DB"
database_id = "48c5e67c-c9c5-40ea-b23c-e7d1fd7ae170"

[env.preview]
[[env.preview.d1_databases]]
binding = "DB"
database_name = "drabaka-db-local"
database_id = "local-dev-db"
